config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

  resources :posts, only: [:new] do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  post '/posts/new', to: 'posts#create' as: 'create_post'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :comments_counter

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_counter

  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true,
    length: { maximum: 250, too_long: 'must not exceed 250 characters' }
  validates :comments_counter, :likes_counter, numericality: { greater_than_or_equal_to: 0 }
  
  
  belongs_to :user, counter_cache: :posts_counter
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def recent_comments
    comments.order('created_at Desc').limit(5)
  end

  def liked?(user_id)
    likes.exists?(user_id: user_id)
  end

  def update_post_counter
    user.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }


  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  def recent_posts
    posts.order('created_at Desc').limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = post.comments.new(text: comment_params[:text], user: current_user)

    respond_to do |format|
      format.html do
        if comment.save
          redirect_to user_post_path(post.user.id, post.id), notice: 'comment successfully added!'
        else
          flash.now[:error] = 'Comment could not be sent!'
          redirect_to user_post_path(post.user.id, post.id), alert: 'Failed to add comment!'
        end
      end
    end
  end

  private

  def comment_params
    params.require(:data).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    like = post.likes.new(user: current_user)

    respond_to do |format|
      format.html do
        if like.save
          redirect_to user_post_path(post.user.id, post.id), notice: 'Liked!'
        else
          redirect_to user_post_path(post.user.id, post.id), alert: 'Could not be liked!'
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where(user_id: params[:user_id]).order(created_at: :desc)
    @user = User.find_by(id: params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comments = @post.comments.all.order('created_at')
    @liked = @post.liked? current_user.id
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      format.html do
        if @post.save
          redirect_to user_post_path(@post.user.id, @post.id), notice: 'Post added successfully'
        else
          flash.now[:alert] = 'Post could not be added'
          render :new
        end
      end
    end
  end

  private

  def post_params
    params.require(:data).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order('created_at')
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_photo(user)
    user.photo.present? ? user.photo : "https://eu.ui-avatars.com/api/?name=#{user.name}&background=random"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice.present? %>
    <div class="notification is-link is-light"><%= notice %></div>
  <% end %>

  <% if alert.present? %>
    <div class="notification is-danger is-light"><%= alert %></div>
  <% end %>
  
  <div class="section">
    <div class="container">
      <%= yield %>
    </div>
  </div>  
  </body>
</html>

app/views/posts/_post.html.erb
<section class="notification my-2">
  <div class="mb-2">
    <p><%= t('post', id: post.id) %></p>
    <p class="is-size-7 is-italic"><%= t('posted_on', date: post.created_at.to_s(:cur_date)) %></p>
  </div>
  <%= link_to user_post_path(post.user.id, post.id) do %>
    <h3 class="title"><%= post.title %></h3>
  <% end %>
  <p class="has-text-right is-size-7">
    <%= t('comments_counter', count: post.comments_counter) %>, <%= t('likes_counter', count: post.likes_counter) %>
  </p>
</section>

app/views/posts/index.html.erb
<%= render partial: "users/user", object: @user %>
<div class="article comments-article">
  <% @posts.each do |post| %>
    <div>
      <%= render partial: "post", object: post %>
      <%= render partial: "shared/comment", collection: post.recent_comments %>
    </div>
  <% end %>
</div>
<button class="button is-small text-center">Pagination</button>

app/views/posts/new.html.erb
<h1 class="title is-5">New Post</h1>
<%= form_with model: @post, url: create_post_path, scope: :data do |f| %>
  <% if @post.errors.any? %>
    <div class="mb-3 p-2 has-background-danger has-text-danger-light">
      <h3><%= pluralize(@post.errors.count, "error") %> occured:</h3>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Post Title", class: "label" %>
    <%= f.text_field :title, placeholder: "Post Title", required: true, class: "input" %>
  </div>
  <div class="field">
    <%= f.text_area :text, placeholder: "Please type in your post...", rows: 16, required: true, class: "textarea has-fixed-size" %>
  </div>
  <%= f.submit "Publish Post", class: "button is-link is-success" %>
<% end %>

app/views/posts/show.html.erb
<section class="content">
  <div class="header">
    <div>
      <p><%= t('post', id: @post.id) %> <%= t('by', name: @user.name) %></p>
    </div>
    <div>
      <p class="is-size-7"><%= t('comments_counter', count: @post.comments_counter) %>, <%= t('likes_counter', count: @post.likes_counter) %></p>
    </div>
  </div>
  <p class="is-size-7 is-italic"><%= t('posted_on', date: @post.created_at.to_s(:cur_date)) %></p>
  <div class="post-title-container">
    <h1 class="title"><%= @post.title %></h1>
    <% if @liked %>
      <%= render partial: "shared/not_like_post", post: @post %>
    <% else %>
      <%= render partial: "shared/like_post", post: @post %>
    <% end %>
  </div>
  <p><%= @post.text %></p>
</section>
  <%= render partial: "shared/new_comment", post: @post %>
  <%= render partial: "shared/comment", collection: @comments %>

app/views/shared/_comment.html.erb
<article class="media">
  <figure class="media-left">
    <p class="picture is-35x35">
      <img class="is-rounded" src=<%= get_photo(comment.user) %> >
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= comment.user.name %></strong> <small><%= t('time_ago', time: time_ago_in_words(comment.created_at)) %></small>
        <br>
        <%= comment.text %>
      </p>
    </div>
  </div>
</article>

app/views/shared/_like_post.html.erb
<%= form_with url: post_likes_path(@post.id) do |f| %>
  <%= f.submit "Like", class: "button is-primary is-small is-outlined" %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar" role="navigation">
  <div class="navbar-end">
    <div class="navbar-item">
      <%= link_to t('create_post'), new_post_path, class: "button is-link" %>
    </div>
  </div>
</nav>

app/views/shared/_new_comment.html.erb
<%= form_with url: post_comments_path(@post.id), scope: :data, class: "mb-6" do |f| %>
  <div class="field">
    <%= f.text_area :text, placeholder: "Please leave your comment", rows: 4, required: true, class: "textarea has-fixed-size" %>
  </div>
  <%= f.submit "Submit", class: "button is-link" %>
<% end %>

app/views/shared/_not_like_post.html.erb
<%= form_with url: post_likes_path(@post.id) do |f| %>
  <%= f.submit "Like", class: "button is-success is-small" %>
<% end %>

app/views/users/_user.html.erb
<section class="media is-align-items-center">
  <div class="media-left">
    <figure class="image is-140x140">
      <img src=<%= get_photo(user) %> alt="user's picture">
    </figure>
  </div>
  <div class="media-content notification">
    <div class="content">
      <h4 class="title is-4"><%= user.name %></h4>
      <p class="has-text-right is-size-8"><%= t('posts_counter', count: user.posts_counter)%></p>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<%= render "shared/nav" %>
<div class="article">
  <% @users.each do |user| %>
    <%= link_to user_path(user.id) do %>
      <%= render partial: "user", object: user %>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render @user %>
<% if @user.bio.present? %>
  <div class="mt-5 notification">
    <h5 class="title is-6">BIO</h5>
    <p class="is-6"><%= @user.bio %></p>
  </div>
<% end %>
<%= render partial: "posts/post", collection: @posts.order(created_at: :desc).limit(3) %>
<%= link_to "See all post", user_posts_path(@user.id), class: "button is-link is-small" %>